storage:
  output_folder: "/path/to/monitoring/results"

default_ssh:
  username: "monitor_user"
  key_path: "~/.ssh/monitor_key"
  port: 22

log_collection:
  delete_after_collection: true  # ログ収集後にサーバーからログを削除するかどうか
  servers:
    - name: "web-server"
      host: "192.168.1.10"
      ssh_port: 22123
      log_paths:
        - "/var/log/nginx/access.log"
        - "/var/log/nginx/error.log" 